// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package msgprotov2

import "strconv"

type ACLCommand int8

const (
	ACLCommandLIST   ACLCommand = 0
	ACLCommandPERMIT ACLCommand = 1
	ACLCommandREVOKE ACLCommand = 2
)

var EnumNamesACLCommand = map[ACLCommand]string{
	ACLCommandLIST:   "LIST",
	ACLCommandPERMIT: "PERMIT",
	ACLCommandREVOKE: "REVOKE",
}

var EnumValuesACLCommand = map[string]ACLCommand{
	"LIST":   ACLCommandLIST,
	"PERMIT": ACLCommandPERMIT,
	"REVOKE": ACLCommandREVOKE,
}

func (v ACLCommand) String() string {
	if s, ok := EnumNamesACLCommand[v]; ok {
		return s
	}
	return "ACLCommand(" + strconv.FormatInt(int64(v), 10) + ")"
}
