// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package msgprotov2

import "strconv"

type ErrType int8

const (
	ErrTypeErrConnection ErrType = 0
	ErrTypeErrBadRequest ErrType = 1
	ErrTypeErrInternal   ErrType = 2
	ErrTypeErrMessage    ErrType = 3
	ErrTypeErrAuth       ErrType = 4
	ErrTypeErrACL        ErrType = 5
)

var EnumNamesErrType = map[ErrType]string{
	ErrTypeErrConnection: "ErrConnection",
	ErrTypeErrBadRequest: "ErrBadRequest",
	ErrTypeErrInternal:   "ErrInternal",
	ErrTypeErrMessage:    "ErrMessage",
	ErrTypeErrAuth:       "ErrAuth",
	ErrTypeErrACL:        "ErrACL",
}

var EnumValuesErrType = map[string]ErrType{
	"ErrConnection": ErrTypeErrConnection,
	"ErrBadRequest": ErrTypeErrBadRequest,
	"ErrInternal":   ErrTypeErrInternal,
	"ErrMessage":    ErrTypeErrMessage,
	"ErrAuth":       ErrTypeErrAuth,
	"ErrACL":        ErrTypeErrACL,
}

func (v ErrType) String() string {
	if s, ok := EnumNamesErrType[v]; ok {
		return s
	}
	return "ErrType(" + strconv.FormatInt(int64(v), 10) + ")"
}
