default:
  image: golang:1.14.4-buster

stages:
  - pre-test
  - test
  - release

.license-check: &license-check |
  git clone https://${GITHUB_TOKEN}:@github.com/aldgate-ventures/license-finder.git
  source ~/.profile
  license_finder --decisions_file ./license-finder/dependency_decisions.yml

.setup: &setup |
  apt-get update
  apt-get -y install libsodium-dev
  tmpdir=$(mktemp -d)
  curl https://download.joinself.com/olm/libself-olm_0.1.14_amd64.deb -o ${tmpdir}/libself-olm_0.1.14_amd64.deb
  curl https://download.joinself.com/omemo/libself-omemo_0.1.1_amd64.deb -o ${tmpdir}/libself-omemo_0.1.1_amd64.deb
  apt-get -y install ${tmpdir}/libself-olm_0.1.14_amd64.deb
  apt-get -y install ${tmpdir}/libself-omemo_0.1.1_amd64.deb

before_script:
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "${SCRIPTS_REPO}" "${SCRIPTS_DIR}"

license-check:
  stage: pre-test
  image: licensefinder/license_finder
  script:
    - ${SCRIPTS_DIR}/git-setup
    - *license-check
  allow_failure: true
  only:
    - branches

unit-test:
  stage: test
  script:
    - *setup
    - go test -v ./...
  only:
    - branches

release:
  stage: release
  image: eu.gcr.io/principal-oxide-204416/deploy
  script:
    - ${SCRIPTS_DIR}/git-setup
    - version=$(${SCRIPTS_DIR}/git-new-version -n joinself)
    - ${SCRIPTS_DIR}/git-release -n joinself -v ${version}
    - ${SCRIPTS_DIR}/slack-release-notification -n joinself -v ${version}
  only:
    - master
