// Copyright 2020 Self Group Ltd. All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: aclcommand.proto

package msgproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACLCommand int32

const (
	ACLCommand_LIST   ACLCommand = 0
	ACLCommand_PERMIT ACLCommand = 1
	ACLCommand_REVOKE ACLCommand = 2
)

// Enum value maps for ACLCommand.
var (
	ACLCommand_name = map[int32]string{
		0: "LIST",
		1: "PERMIT",
		2: "REVOKE",
	}
	ACLCommand_value = map[string]int32{
		"LIST":   0,
		"PERMIT": 1,
		"REVOKE": 2,
	}
)

func (x ACLCommand) Enum() *ACLCommand {
	p := new(ACLCommand)
	*p = x
	return p
}

func (x ACLCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACLCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_aclcommand_proto_enumTypes[0].Descriptor()
}

func (ACLCommand) Type() protoreflect.EnumType {
	return &file_aclcommand_proto_enumTypes[0]
}

func (x ACLCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACLCommand.Descriptor instead.
func (ACLCommand) EnumDescriptor() ([]byte, []int) {
	return file_aclcommand_proto_rawDescGZIP(), []int{0}
}

var File_aclcommand_proto protoreflect.FileDescriptor

var file_aclcommand_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x63, 0x6c, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x6d, 0x73, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x2e, 0x0a, 0x0a,
	0x41, 0x43, 0x4c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49,
	0x53, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x54, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x56, 0x4f, 0x4b, 0x45, 0x10, 0x02, 0x42, 0x52, 0x0a, 0x17,
	0x6e, 0x65, 0x74, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x69, 0x64, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x64, 0x67, 0x61, 0x74, 0x65, 0x2d, 0x76, 0x65, 0x6e, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aclcommand_proto_rawDescOnce sync.Once
	file_aclcommand_proto_rawDescData = file_aclcommand_proto_rawDesc
)

func file_aclcommand_proto_rawDescGZIP() []byte {
	file_aclcommand_proto_rawDescOnce.Do(func() {
		file_aclcommand_proto_rawDescData = protoimpl.X.CompressGZIP(file_aclcommand_proto_rawDescData)
	})
	return file_aclcommand_proto_rawDescData
}

var file_aclcommand_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aclcommand_proto_goTypes = []interface{}{
	(ACLCommand)(0), // 0: msgproto.ACLCommand
}
var file_aclcommand_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aclcommand_proto_init() }
func file_aclcommand_proto_init() {
	if File_aclcommand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aclcommand_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aclcommand_proto_goTypes,
		DependencyIndexes: file_aclcommand_proto_depIdxs,
		EnumInfos:         file_aclcommand_proto_enumTypes,
	}.Build()
	File_aclcommand_proto = out.File
	file_aclcommand_proto_rawDesc = nil
	file_aclcommand_proto_goTypes = nil
	file_aclcommand_proto_depIdxs = nil
}
