// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package msgproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Auth struct {
	Type                 MsgType  `protobuf:"varint,1,opt,name=type,proto3,enum=msgproto.MsgType" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Device               string   `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Offset               uint64   `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_MSG
}

func (m *Auth) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Auth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Auth) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Auth) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*Auth)(nil), "msgproto.Auth")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x2d, 0x4e, 0x07, 0xb3, 0xa4, 0x78, 0x73,
	0x8b, 0xd3, 0x4b, 0x2a, 0x0b, 0x52, 0x21, 0x12, 0x4a, 0xcd, 0x8c, 0x5c, 0x2c, 0x8e, 0xa5, 0x25,
	0x19, 0x42, 0xaa, 0x5c, 0x2c, 0x20, 0x61, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x41, 0x3d,
	0x98, 0x06, 0x3d, 0xdf, 0xe2, 0xf4, 0x90, 0xca, 0x82, 0xd4, 0x20, 0xb0, 0xb4, 0x10, 0x1f, 0x17,
	0x53, 0x66, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x08, 0x17,
	0x6b, 0x49, 0x7e, 0x76, 0x6a, 0x9e, 0x04, 0x33, 0x58, 0x08, 0xc2, 0x11, 0x12, 0xe3, 0x62, 0x4b,
	0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0x95, 0x60, 0x01, 0x0b, 0x43, 0x79, 0x20, 0xf1, 0xfc, 0xb4, 0xb4,
	0xe2, 0xd4, 0x12, 0x09, 0x56, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x28, 0xcf, 0x49, 0x92, 0x4b, 0x3c,
	0x2f, 0xb5, 0x44, 0xaf, 0x38, 0x35, 0x27, 0x2d, 0x33, 0x45, 0x2f, 0xb1, 0xa0, 0x00, 0xe2, 0xba,
	0xe4, 0xfc, 0x9c, 0x24, 0x36, 0x30, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x5c, 0x04,
	0x68, 0xce, 0x00, 0x00, 0x00,
}
