// Copyright 2020 Self Group Ltd. All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: errtype.proto

package msgproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ErrType int32

const (
	ErrType_ErrConnection ErrType = 0
	ErrType_ErrBadRequest ErrType = 1
	ErrType_ErrInternal   ErrType = 2
	ErrType_ErrMessage    ErrType = 3
	ErrType_ErrAuth       ErrType = 4
	ErrType_ErrACL        ErrType = 5
)

// Enum value maps for ErrType.
var (
	ErrType_name = map[int32]string{
		0: "ErrConnection",
		1: "ErrBadRequest",
		2: "ErrInternal",
		3: "ErrMessage",
		4: "ErrAuth",
		5: "ErrACL",
	}
	ErrType_value = map[string]int32{
		"ErrConnection": 0,
		"ErrBadRequest": 1,
		"ErrInternal":   2,
		"ErrMessage":    3,
		"ErrAuth":       4,
		"ErrACL":        5,
	}
)

func (x ErrType) Enum() *ErrType {
	p := new(ErrType)
	*p = x
	return p
}

func (x ErrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrType) Descriptor() protoreflect.EnumDescriptor {
	return file_errtype_proto_enumTypes[0].Descriptor()
}

func (ErrType) Type() protoreflect.EnumType {
	return &file_errtype_proto_enumTypes[0]
}

func (x ErrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrType.Descriptor instead.
func (ErrType) EnumDescriptor() ([]byte, []int) {
	return file_errtype_proto_rawDescGZIP(), []int{0}
}

var File_errtype_proto protoreflect.FileDescriptor

var file_errtype_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6d, 0x73, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x69, 0x0a, 0x07, 0x45, 0x72, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x42, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x72,
	0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x45,
	0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x45,
	0x72, 0x72, 0x41, 0x75, 0x74, 0x68, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x41,
	0x43, 0x4c, 0x10, 0x05, 0x42, 0x19, 0x0a, 0x17, 0x6e, 0x65, 0x74, 0x2e, 0x73, 0x65, 0x6c, 0x66,
	0x69, 0x64, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errtype_proto_rawDescOnce sync.Once
	file_errtype_proto_rawDescData = file_errtype_proto_rawDesc
)

func file_errtype_proto_rawDescGZIP() []byte {
	file_errtype_proto_rawDescOnce.Do(func() {
		file_errtype_proto_rawDescData = protoimpl.X.CompressGZIP(file_errtype_proto_rawDescData)
	})
	return file_errtype_proto_rawDescData
}

var file_errtype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errtype_proto_goTypes = []interface{}{
	(ErrType)(0), // 0: msgproto.ErrType
}
var file_errtype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errtype_proto_init() }
func file_errtype_proto_init() {
	if File_errtype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errtype_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errtype_proto_goTypes,
		DependencyIndexes: file_errtype_proto_depIdxs,
		EnumInfos:         file_errtype_proto_enumTypes,
	}.Build()
	File_errtype_proto = out.File
	file_errtype_proto_rawDesc = nil
	file_errtype_proto_goTypes = nil
	file_errtype_proto_depIdxs = nil
}
