// Code generated by protoc-gen-go. DO NOT EDIT.
// source: header.proto

package msgproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Type                 MsgType  `protobuf:"varint,1,opt,name=type,proto3,enum=msgproto.MsgType" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_MSG
}

func (m *Header) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Header)(nil), "msgproto.Header")
}

func init() { proto.RegisterFile("header.proto", fileDescriptor_6398613e36d6c2ce) }

var fileDescriptor_6398613e36d6c2ce = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0x4d, 0x4c,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x2d, 0x4e, 0x07, 0xb3, 0xa4,
	0x78, 0x73, 0x8b, 0xd3, 0x4b, 0x2a, 0x0b, 0x52, 0x21, 0x12, 0x4a, 0xf6, 0x5c, 0x6c, 0x1e, 0x60,
	0x85, 0x42, 0xaa, 0x5c, 0x2c, 0x20, 0x71, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x41, 0x3d,
	0x98, 0x0e, 0x3d, 0xdf, 0xe2, 0xf4, 0x90, 0xca, 0x82, 0xd4, 0x20, 0xb0, 0xb4, 0x10, 0x1f, 0x17,
	0x53, 0x66, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x93, 0x24, 0x97,
	0x78, 0x5e, 0x6a, 0x89, 0x5e, 0x71, 0x6a, 0x4e, 0x5a, 0x66, 0x8a, 0x5e, 0x62, 0x41, 0x01, 0xc4,
	0xe0, 0xe4, 0xfc, 0x9c, 0x24, 0x36, 0x30, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x24,
	0x8c, 0xc1, 0x8b, 0x00, 0x00, 0x00,
}
