// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package msgproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Notification struct {
	Type                 MsgType  `protobuf:"varint,1,opt,name=type,proto3,enum=msgproto.MsgType" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Errtype              ErrType  `protobuf:"varint,4,opt,name=errtype,proto3,enum=msgproto.ErrType" json:"errtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_MSG
}

func (m *Notification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notification) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Notification) GetErrtype() ErrType {
	if m != nil {
		return m.Errtype
	}
	return ErrType_ErrConnection
}

func init() {
	proto.RegisterType((*Notification)(nil), "msgproto.Notification")
}

func init() { proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07) }

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcb, 0x2f, 0xc9,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0xc8, 0x2d, 0x4e, 0x07, 0xb3, 0xa4, 0x78, 0x73, 0x8b, 0xd3, 0x4b, 0x2a, 0x0b, 0x52, 0xf5, 0xa0,
	0xdc, 0xd4, 0xa2, 0x22, 0x04, 0x57, 0xa9, 0x83, 0x91, 0x8b, 0xc7, 0x0f, 0x49, 0xbb, 0x90, 0x2a,
	0x17, 0x0b, 0x48, 0x5a, 0x82, 0x51, 0x81, 0x51, 0x83, 0xcf, 0x48, 0x50, 0x0f, 0x66, 0x8e, 0x9e,
	0x6f, 0x71, 0x7a, 0x48, 0x65, 0x41, 0x6a, 0x10, 0x58, 0x5a, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45,
	0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x88, 0x29, 0x33, 0x45, 0x48, 0x84, 0x8b, 0x35, 0xb5, 0xa8,
	0x28, 0xbf, 0x48, 0x82, 0x19, 0x2c, 0x04, 0xe1, 0x08, 0x69, 0x73, 0xb1, 0x43, 0xad, 0x93, 0x60,
	0x41, 0x37, 0xcf, 0xb5, 0xa8, 0x08, 0x6c, 0x1e, 0x4c, 0x85, 0x93, 0x24, 0x97, 0x78, 0x5e, 0x6a,
	0x89, 0x5e, 0x71, 0x6a, 0x4e, 0x5a, 0x66, 0x8a, 0x5e, 0x62, 0x41, 0x01, 0xc4, 0x89, 0xc9, 0xf9,
	0x39, 0x49, 0x6c, 0x60, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x19, 0x38, 0x81, 0xea,
	0x00, 0x00, 0x00,
}
